language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.2"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - phpunit --verbose --coverage-clover=coverage/coverage.clover